DROP TABLE EMPLOYEE CASCADE CONSTRAINTS;
DROP TABLE COMPANY CASCADE CONSTRAINTS;
DROP TABLE CONTRACT CASCADE CONSTRAINTS;
DROP TABLE MATERIAL CASCADE CONSTRAINTS;
DROP TABLE ITEM CASCADE CONSTRAINTS;
DROP TABLE BOM CASCADE CONSTRAINTS;
DROP TABLE WORKER CASCADE CONSTRAINTS;
DROP TABLE WORK CASCADE CONSTRAINTS;
DROP TABLE PROCESS CASCADE CONSTRAINTS;
DROP TABLE PROCESS_INFO CASCADE CONSTRAINTS;
DROP TABLE MACHINE_INFO CASCADE CONSTRAINTS;
DROP TABLE MACHINE_WORK CASCADE CONSTRAINTS;
DROP TABLE MACHINE_REPAIR CASCADE CONSTRAINTS;
DROP TABLE MACHINE_CHECK_RECORD CASCADE CONSTRAINTS;
DROP TABLE MACHINE_CHECK_INFO CASCADE CONSTRAINTS;
DROP TABLE INVENTORY CASCADE CONSTRAINTS;
DROP TABLE QUALITY_INSPECTION CASCADE CONSTRAINTS;
DROP TABLE QUALITY_STANDARD CASCADE CONSTRAINTS;
DROP TABLE INSTRUCTION CASCADE CONSTRAINTS;


DELETE FROM EMPLOYEE;
DELETE FROM COMPANY;
DELETE FROM CONTRACT;
DELETE FROM MATERIAL;
DELETE FROM ITEM;
DELETE FROM BOM;
DELETE FROM WORKER;
DELETE FROM WORK;
DELETE FROM PROCESS;
DELETE FROM PROCESS_INFO;
DELETE FROM MACHINE_INFO;
DELETE FROM MACHINE_WORK;
DELETE FROM MACHINE_REPAIR;
DELETE FROM MACHINE_CHECK_RECORD;
DELETE FROM MACHINE_CHECK_INFO;
DELETE FROM INVENTORY;
DELETE FROM QUALITY_INSPECTION;
DELETE FROM QUALITY_STANDARD;
DELETE FROM INSTRUCTION;


DROP SEQUENCE EMPLOYEE_SEQ;
DROP SEQUENCE COMPANY_SEQ;
DROP SEQUENCE CONTRACT_SEQ;
DROP SEQUENCE MATERIAL_SEQ;
DROP SEQUENCE ITEM_SEQ;
DROP SEQUENCE WORKER_SEQ;
DROP SEQUENCE WORK_SEQ;
DROP SEQUENCE PROCESS_SEQ;
DROP SEQUENCE PROCESS_INFO_SEQ;
DROP SEQUENCE MACHINE_INFO_SEQ;
DROP SEQUENCE MACHINE_WORK_SEQ;
DROP SEQUENCE MACHINE_REPAIR_SEQ;
DROP SEQUENCE MACHINE_CHECK_RECORD_SEQ;
DROP SEQUENCE MACHINE_CHECK_INFO_SEQ;
DROP SEQUENCE INVENTORY_SEQ;
DROP SEQUENCE QUALITY_INSPECTION_SEQ;
DROP SEQUENCE QUALITY_STANDARD_SEQ;
DROP SEQUENCE INSTRUCTION_SEQ;



-- PROCESS_INFO 시퀀스
create sequence PROCESS_INFO_SEQ
increment by 1
start with 1066
maxvalue 10000
nocache
;
-- QUALITY_STANDARD 시퀀스
create sequence QUALITY_STANDARD_SEQ
increment by 1
start with 10014
maxvalue 100000
nocache
;
-- EMPLOYEE 시퀀스
create sequence EMPLOYEE_SEQ
increment by 1
start with 100138
maxvalue 200000
nocache
;
-- COMPANY 시퀀스
create sequence COMPANY_SEQ
increment by 1
start with 200071
maxvalue 300000
nocache
;
-- INSTRUCTION 시퀀스
create sequence INSTRUCTION_SEQ
increment by 1
start with 300001
maxvalue 1000000
nocache
;
-- CONTRACT 시퀀스
create sequence CONTRACT_SEQ
increment by 1
start with 1000031
maxvalue 2000000
nocache
;
-- MACHINE_INFO 시퀀스
create sequence MACHINE_INFO_SEQ
increment by 1
start with 6000104
maxvalue 8000000
nocache
;
-- MACHINE_CHECK_INFO 시퀀스
create sequence MACHINE_CHECK_INFO_SEQ
increment by 1
start with 8000038
maxvalue 10000000
nocache
;
-- ITEM 시퀀스
create sequence ITEM_SEQ
increment by 1
start with 10000106
maxvalue 20000000
nocache
;
-- MATERIAL 시퀀스
create sequence MATERIAL_SEQ
increment by 1
start with 20000043
maxvalue 30000000
nocache
;
-- WORK 시퀀스
create sequence WORK_SEQ
increment by 1
start with 1
maxvalue 9999999999
nocache
;
-- MACHINE_REPAIR 시퀀스
create sequence MACHINE_REPAIR_SEQ
increment by 1
start with 1
maxvalue 9999999999
nocache
;
-- MACHINE_CHECK_RECORD 시퀀스
create sequence MACHINE_CHECK_RECORD_SEQ
increment by 1
start with 1
maxvalue 9999999999
nocache
;
-- QUALITY_INSPECTION 시퀀스
create sequence QUALITY_INSPECTION_SEQ
increment by 1
start with 1
maxvalue 9999999999
nocache
;


CREATE TABLE EMPLOYEE (
    E_ID NUMBER(10) NOT NULL,
    E_NAME VARCHAR2(4char) NOT NULL,
    E_EMAIL VARCHAR2(50char) NOT NULL,
    E_PH NUMBER(11) NOT NULL,
    E_PWD VARCHAR2(10char) NOT NULL,
    E_DP_NAME VARCHAR2(10char) NOT NULL,
    E_ROLE VARCHAR2(3char) NOT NULL,
    PRIMARY KEY (E_ID)
);

CREATE TABLE COMPANY (
    C_ID NUMBER(10) NOT NULL,
    C_NAME VARCHAR2(10char) NOT NULL,
    C_EMAIL VARCHAR2(50char) NOT NULL,
    C_DIV VARCHAR2(4char) NOT NULL,
    C_ADDRESS VARCHAR2(100char) NOT NULL,
    C_PH NUMBER(11) NOT NULL,
    PRIMARY KEY (C_ID)
);

CREATE TABLE CONTRACT (
    CT_ID NUMBER(10) NOT NULL,
    CT_Company_ID NUMBER(10) NOT NULL,
    CT_Material_ID NUMBER(10),
    CT_ITEM_ID NUMBER(10),
    CT_DIV VARCHAR2(10char) NOT NULL,
    CT_AMOUT_MONEY NUMBER(10) NOT NULL,
    CT_DATE DATE NOT NULL,
    CT_UNIT VARCHAR2(5char) NOT NULL,
    CT_QUANTITY NUMBER(10) NOT NULL,
    CT_REAL_QUANTITY NUMBER(10) NOT NULL,
    CT_IB_DATE DATE,
    CT_OB_DATE DATE,
    CT_REAL_IB_DATE DATE,
    CT_REAL_OB_DATE DATE,
    PRIMARY KEY (CT_ID)
);

CREATE TABLE MATERIAL (
    M_ID NUMBER(10) NOT NULL,
    M_NAME VARCHAR2(10char) NOT NULL,
    M_USES VARCHAR2(10char) NOT NULL,
    PRIMARY KEY (M_ID)
);

CREATE TABLE ITEM (
    I_ID NUMBER(10) NOT NULL,
    I_NAME VARCHAR2(50char) NOT NULL,
    I_COLOR VARCHAR2(10char) NOT NULL,
    I_STANDARD VARCHAR2(50char) NOT NULL,
    I_TYPE VARCHAR2(10char) NOT NULL,
    I_USES VARCHAR2(10char) NOT NULL,
    PRIMARY KEY (I_ID)
);

CREATE TABLE BOM (
    B_ITEM_ID NUMBER(10) NOT NULL,
    B_MATERIAL_ID NUMBER(10) NOT NULL,
    B_UNIT VARCHAR2(5char) NOT NULL,
    B_MATERIAL_QUANTITY NUMBER(10) NOT NULL
);

CREATE TABLE WORKER (
    WR_EMP_ID NUMBER(10) NOT NULL,
    WR_WORK_ID NUMBER(10) NOT NULL,
    WR_MACHINE_ID NUMBER(10) NOT NULL,
    WR_DATE DATE NOT NULL,
    WR_START_TIME TIMESTAMP NOT NULL,
    WR_END_TIME TIMESTAMP NOT NULL
);

CREATE TABLE WORK (
    W_ID NUMBER(10) NOT NULL,
    W_BOM_ITEM_ID NUMBER(10) NOT NULL,
    W_LOT_ID NUMBER(10) NOT NULL,
    W_PI_ID NUMBER(10) NOT NULL,
    W_MI_ID NUMBER(10),
    W_QI_ID NUMBER(10),
    W_START_TIME TIMESTAMP,
    W_END_TIME TIMESTAMP,
    W_TIME NUMBER(10) NOT NULL,
    W_STATUS VARCHAR2(10char) NOT NULL,
    W_PLAN_QUANTITY NUMBER(10) NOT NULL,
    W_ITEM_QUANTITY NUMBER(10) NOT NULL,
    W_NOTE VARCHAR2(300char)
);

CREATE TABLE PROCESS (
    P_LOT_ID NUMBER(10) NOT NULL,
    P_PI_ID NUMBER(10) NOT NULL,
    P_B_ITEM_ID NUMBER(10) NOT NULL,
    P_PLAN_QUANTITY NUMBER(10) NOT NULL,
    P_ITME_QUANTITY NUMBER(10) DEFAULT 0 NOT NULL,
    P_DEFECTIVE_QUANTITY NUMBER(10) DEFAULT 0 NOT NULL,
    P_START_DATE DATE NOT NULL,
    P_END_DATE DATE,
    P_STATUS VARCHAR2(10char) NOT NULL,
    P_NOTE VARCHAR2(500char)
);

CREATE TABLE PROCESS_INFO (
    PI_ID NUMBER(10) NOT NULL,
    PI_MACHINE_ID NUMBER(10),
    PI_NAME VARCHAR2(10char) NOT NULL,
    PI_SEQ VARCHAR2(10char) NOT NULL
);

CREATE TABLE MACHINE_INFO (
    MI_ID NUMBER(10) NOT NULL,
    MI_NAME VARCHAR2(50char) NOT NULL,
    MI_POSITION VARCHAR2(50char),
    MI_TYPE VARCHAR2(50char) NOT NULL,
    PRIMARY KEY (MI_ID)
);

CREATE TABLE MACHINE_WORK (
    MW_MI_ID NUMBER(10) NOT NULL,
    MW_STATUS VARCHAR2(10char) NOT NULL,
    MW_CONDITION VARCHAR2(10char) NOT NULL,
    PRIMARY KEY (MW_MI_ID)
);

CREATE TABLE MACHINE_REPAIR (
    MR_ID NUMBER(10) NOT NULL,
    MR_MI_ID NUMBER(10) NOT NULL,
    MR_MCR_ID NUMBER(10) NOT NULL,
    MR_DATE DATE DEFAULT SYSDATE NOT NULL,
    PRIMARY KEY (MR_ID)
);

CREATE TABLE MACHINE_CHECK_RECORD (
    MCR_ID NUMBER(10) NOT NULL,
    MCR_MCI_ID NUMBER(10) NOT NULL,
    MCR_MI_ID NUMBER(10) NOT NULL,
    MCR_EMP_ID NUMBER(10) NOT NULL,
    MCR_DATE DATE NOT NULL,
    MCR_ANSWER VARCHAR2(1char) NOT NULL,
    MCR_NOTE VARCHAR2(100char)
);

CREATE TABLE MACHINE_CHECK_INFO (
    MCI_ID NUMBER(10) NOT NULL,
    MCI_MI_ID NUMBER(10) NOT NULL,
    MCI_DIV VARCHAR2(10char) NOT NULL,
    MCI_CONDITION VARCHAR2(100char) NOT NULL,
    MCI_METHOD VARCHAR2(10char) NOT NULL
);

CREATE TABLE INVENTORY (
    INV_MATERIAL_ID NUMBER(10),
    INV_ITEM_ID NUMBER(10),
    INV_INS_ID NUMBER(10),
    INV_PRO_LOT_ID NUMBER(10),
    INV_QUANTITY NUMBER(10) NOT NULL,
    INV_UNIT VARCHAR2(10char) NOT NULL
);

CREATE TABLE QUALITY_INSPECTION (
    QI_ID NUMBER(10) NOT NULL,
    QI_CT_ID NUMBER(10),
    QI_PRO_LOT_ID NUMBER(10),
    QI_PI_ID NUMBER(10),
    QI_WORK_ID NUMBER(10),
    QI_MATERIAL_ID NUMBER(10),
    QI_ITEM_ID NUMBER(10),
    QI_QS_ID NUMBER(10) NOT NULL,
    QI_INSPECTION_QUANTITY NUMBER(10),
    QI_PASSED_QUANTITY NUMBER(10) NOT NULL,
    QI_DFT_QUANTITY NUMBER(10) DEFAULT 0 NOT NULL,
    QI_DATE DATE DEFAULT SYSDATE NOT NULL,
    QI_NOTE VARCHAR2(300char),
    PRIMARY KEY (QI_ID)
);

CREATE TABLE QUALITY_STANDARD (
    QS_ID NUMBER(10) NOT NULL,
    QS_DF_DIV1 VARCHAR2(20char) NOT NULL,
    QS_DF_DIV2 VARCHAR2(20char),
    PRIMARY KEY (QS_ID)
);

CREATE TABLE INSTRUCTION (
    INS_LOT_ID NUMBER(10) NOT NULL,
    INS_ITEM_ID NUMBER(10) NOT NULL,
    INS_EMP_ID NUMBER(10) NOT NULL,
    INS_CT_ID NUMBER(10) NOT NULL,
    INS_LOT_SIZE NUMBER(10) NOT NULL,
    INS_START_DATE DATE NOT NULL,
    INS_END_DATE DATE NOT NULL,
    PRIMARY KEY (INS_LOT_ID)
);

ALTER TABLE CONTRACT ADD FOREIGN KEY (CT_Company_ID) REFERENCES COMPANY(C_ID);
ALTER TABLE CONTRACT ADD FOREIGN KEY (CT_ITEM_ID) REFERENCES ITEM(I_ID);
ALTER TABLE CONTRACT ADD FOREIGN KEY (CT_Material_ID) REFERENCES MATERIAL(M_ID);
ALTER TABLE BOM ADD FOREIGN KEY (B_ITEM_ID) REFERENCES ITEM(I_ID);
ALTER TABLE BOM ADD FOREIGN KEY (B_MATERIAL_ID) REFERENCES MATERIAL(M_ID);
ALTER TABLE WORKER ADD FOREIGN KEY (WR_EMP_ID) REFERENCES EMPLOYEE(E_ID);
ALTER TABLE WORKER ADD FOREIGN KEY (WR_MACHINE_ID) REFERENCES MACHINE_INFO(MI_ID);
ALTER TABLE WORK ADD FOREIGN KEY (W_LOT_ID) REFERENCES INSTRUCTION(INS_LOT_ID);
ALTER TABLE WORK ADD FOREIGN KEY (W_MI_ID) REFERENCES MACHINE_INFO(MI_ID);
ALTER TABLE PROCESS_INFO ADD FOREIGN KEY (PI_MACHINE_ID) REFERENCES MACHINE_INFO(MI_ID);
ALTER TABLE MACHINE_WORK ADD FOREIGN KEY (MW_MI_ID) REFERENCES MACHINE_INFO(MI_ID);
ALTER TABLE MACHINE_REPAIR ADD FOREIGN KEY (MR_MI_ID) REFERENCES MACHINE_INFO(MI_ID);
ALTER TABLE MACHINE_CHECK_RECORD ADD FOREIGN KEY (MCR_MI_ID) REFERENCES MACHINE_INFO(MI_ID);
ALTER TABLE MACHINE_CHECK_RECORD ADD FOREIGN KEY (MCR_EMP_ID) REFERENCES EMPLOYEE(E_ID);
ALTER TABLE MACHINE_CHECK_INFO ADD FOREIGN KEY (MCI_MI_ID) REFERENCES MACHINE_INFO(MI_ID);
ALTER TABLE INVENTORY ADD FOREIGN KEY (INV_ITEM_ID) REFERENCES ITEM(I_ID);
ALTER TABLE INVENTORY ADD FOREIGN KEY (INV_INS_ID) REFERENCES CONTRACT(CT_ID);
ALTER TABLE INVENTORY ADD FOREIGN KEY (INV_PRO_LOT_ID) REFERENCES INSTRUCTION(P_LOT_ID);
ALTER TABLE QUALITY_INSPECTION ADD FOREIGN KEY (QI_PRO_LOT_ID) REFERENCES INSTRUCTION(INS_LOT_ID);
ALTER TABLE QUALITY_INSPECTION ADD FOREIGN KEY (QI_MATERIAL_ID) REFERENCES MATERIAL(M_ID);
ALTER TABLE QUALITY_INSPECTION ADD FOREIGN KEY (QI_ITEM_ID) REFERENCES ITEM(I_ID);
ALTER TABLE INSTRUCTION ADD FOREIGN KEY (INS_ITEM_ID) REFERENCES ITEM(I_ID);
ALTER TABLE INSTRUCTION ADD FOREIGN KEY (INS_EMP_ID) REFERENCES EMPLOYEE(E_ID);
ALTER TABLE INSTRUCTION ADD FOREIGN KEY (INS_CT_ID) REFERENCES CONTRACT(CT_ID);

ALTER TABLE MACHINE_WORK MODIFY MW_STATUS DEFAULT '비가동';
ALTER TABLE MACHINE_WORK MODIFY MW_CONDITION DEFAULT '이상없음';
ALTER TABLE EMPLOYEE MODIFY E_PWD DEFAULT '123123 ';
ALTER TABLE EMPLOYEE MODIFY E_ROLE DEFAULT '사원';

COMMIT;